Shader "Roystan/Toon/Water Tut Ortho"
{
    Properties
    {
        // What color the water will sample when the surface below is shallow.
        _DepthGradientShallow("Depth Gradient Shallow", Color) = (0.325, 0.807, 0.971, 0.725)

        // What color the water will sample when the surface below is at its deepest.
        _DepthGradientDeep("Depth Gradient Deep", Color) = (0.086, 0.407, 1, 0.749)

        // Maximum distance the surface below the water will affect the color gradient.
        _DepthMaxDistance("Depth Maximum Distance", Float) = 1

        // Color to render the foam generated by objects intersecting the surface.
        _FoamColor("Foam Color", Color) = (1,1,1,1)

        // Noise texture used to generate waves.
        _SurfaceNoise("Surface Noise", 2D) = "white" {}

        // Speed, in UVs per second the noise will scroll. Only the xy components are used.
        _SurfaceNoiseScroll("Surface Noise Scroll Amount", Vector) = (0.03, 0.03, 0, 0)

        // Values in the noise texture above this cutoff are rendered on the surface.
        _SurfaceNoiseCutoff("Surface Noise Cutoff", Range(0, 1)) = 0.777

        // Red and green channels of this texture are used to offset the
        // noise texture to create distortion in the waves.
        _SurfaceDistortion("Surface Distortion", 2D) = "white" {}   

        // Multiplies the distortion by this value.
        _SurfaceDistortionAmount("Surface Distortion Amount", Range(0, 1)) = 0.27

        // Control the distance that surfaces below the water will contribute
        // to foam being rendered.
        _FoamMaxDistance("Foam Maximum Distance", Float) = 0.4
        _FoamMinDistance("Foam Minimum Distance", Float) = 0.04     
    }
    SubShader
    {
        Tags
        {
            "Queue" = "Transparent"
            "RenderType" = "Transparent"
            "RenderPipeline" = "UniversalPipeline"
        }

        Pass
        {
            Tags { "LightMode" = "UniversalForward" }

            Blend SrcAlpha OneMinusSrcAlpha
            ZWrite Off

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag

            // Директивы для работы теней и куки в URP
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN
            #pragma multi_compile _ _LIGHT_COOKIES

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"

            #define SMOOTHSTEP_AA 0.01

            CBUFFER_START(UnityPerMaterial)
                float4 _DepthGradientShallow;
                float4 _DepthGradientDeep;
                float4 _FoamColor;
                float _DepthMaxDistance;
                float _FoamMaxDistance;
                float _FoamMinDistance;
                float _SurfaceNoiseCutoff;
                float _SurfaceDistortionAmount;
                float2 _SurfaceNoiseScroll;
                float4 _SurfaceNoise_ST;
                float4 _SurfaceDistortion_ST;
            CBUFFER_END

            TEXTURE2D(_SurfaceNoise);
            SAMPLER(sampler_SurfaceNoise);

            TEXTURE2D(_SurfaceDistortion);
            SAMPLER(sampler_SurfaceDistortion);

            // Текстуры глубины и нормалей
            TEXTURE2D(_CameraDepthTexture);
            SAMPLER(sampler_CameraDepthTexture);

            TEXTURE2D(_CameraNormalsTexture);
            SAMPLER(sampler_CameraNormalsTexture);

            // Оригинальный алгоритм альфа-блендинга
            float4 alphaBlend(float4 top, float4 bottom)
            {
                float3 color = (top.rgb * top.a) + (bottom.rgb * (1.0 - top.a));
                float alpha = top.a + bottom.a * (1.0 - top.a);

                return float4(color, alpha);
            }

            struct appdata
            {
                float4 vertex : POSITION;
                float4 uv : TEXCOORD0;
                float3 normal : NORMAL;
            };

            struct v2f
            {
                float4 vertex : SV_POSITION;    
                float2 noiseUV : TEXCOORD0;
                float2 distortUV : TEXCOORD1;
                float4 screenPosition : TEXCOORD2;
                float3 viewNormal : NORMAL;
                float eyeDepth : TEXCOORD3;
                float3 positionWS : TEXCOORD4;
            };

            v2f vert (appdata v)
            {
                v2f o;

                VertexPositionInputs vertexInput = GetVertexPositionInputs(v.vertex.xyz);
                VertexNormalInputs normalInput = GetVertexNormalInputs(v.normal);

                o.vertex = vertexInput.positionCS;
                o.positionWS = vertexInput.positionWS;
                o.screenPosition = ComputeScreenPos(o.vertex);
                
                o.distortUV = v.uv.xy * _SurfaceDistortion_ST.xy + _SurfaceDistortion_ST.zw;
                o.noiseUV = v.uv.xy * _SurfaceNoise_ST.xy + _SurfaceNoise_ST.zw;
                
                // Эквивалент оригинального COMPUTE_VIEW_NORMAL
                o.viewNormal = TransformWorldToViewNormal(normalInput.normalWS);
                
                // Эквивалент оригинального расчета eyeDepth
                o.eyeDepth = -TransformWorldToView(vertexInput.positionWS).z;

                return o;
            }

            float4 frag (v2f i) : SV_Target
            {
                float2 screenUV = i.screenPosition.xy / i.screenPosition.w;

                // Оригинальная логика чтения глубины
                float existingDepth01 = SAMPLE_TEXTURE2D(_CameraDepthTexture, sampler_CameraDepthTexture, screenUV).r;
                
                float existingDepthLinear = 0;
                
                if (unity_OrthoParams.w > 0.0)
                {
                    #if UNITY_REVERSED_Z
                        float rawDepth = 1.0 - existingDepth01;
                    #else
                        float rawDepth = existingDepth01;
                    #endif
                    existingDepthLinear = _ProjectionParams.y + rawDepth * (_ProjectionParams.z - _ProjectionParams.y);
                }
                else
                {
                    existingDepthLinear = LinearEyeDepth(existingDepth01, _ZBufferParams);
                }

                float depthDifference = existingDepthLinear - i.eyeDepth;

                float waterDepthDifference01 = saturate(depthDifference / _DepthMaxDistance);
                float4 waterColor = lerp(_DepthGradientShallow, _DepthGradientDeep, waterDepthDifference01);
                
                // Оригинальная логика нормалей
                float3 existingNormal = SAMPLE_TEXTURE2D(_CameraNormalsTexture, sampler_CameraNormalsTexture, screenUV).xyz;
                
                float3 normalDot = saturate(dot(existingNormal, i.viewNormal));
                float foamDistance = lerp(_FoamMaxDistance, _FoamMinDistance, normalDot);
                float foamDepthDifference01 = saturate(depthDifference / foamDistance);

                float surfaceNoiseCutoff = foamDepthDifference01 * _SurfaceNoiseCutoff;

                float2 distortSample = (SAMPLE_TEXTURE2D(_SurfaceDistortion, sampler_SurfaceDistortion, i.distortUV).xy * 2.0 - 1.0) * _SurfaceDistortionAmount;

                float2 noiseUV = float2((i.noiseUV.x + _Time.y * _SurfaceNoiseScroll.x) + distortSample.x, 
                (i.noiseUV.y + _Time.y * _SurfaceNoiseScroll.y) + distortSample.y);
                float surfaceNoiseSample = SAMPLE_TEXTURE2D(_SurfaceNoise, sampler_SurfaceNoise, noiseUV).r;

                float surfaceNoise = smoothstep(surfaceNoiseCutoff - SMOOTHSTEP_AA, surfaceNoiseCutoff + SMOOTHSTEP_AA, surfaceNoiseSample);

                float4 surfaceNoiseColor = _FoamColor;
                surfaceNoiseColor.a *= surfaceNoise;

                // Применение оригинального альфа-блендинга
                float4 finalColor = alphaBlend(surfaceNoiseColor, waterColor);

                // --- ЛОГИКА ТЕНЕЙ И COOKIES ДЛЯ URP ---
                float4 shadowCoord = TransformWorldToShadowCoord(i.positionWS);
                Light mainLight = GetMainLight(shadowCoord, i.positionWS, 1.0);

                // Применяем тени
                finalColor.rgb *= mainLight.shadowAttenuation;

                // Применяем Cookies (если они есть у Directional Light)
                #if defined(_LIGHT_COOKIES)
                    float3 cookieColor = SampleMainLightCookie(i.positionWS);
                    finalColor.rgb *= cookieColor;
                #endif

                return finalColor;
            }
            ENDHLSL
        }
    }
}